input_lvs = [
    {
        'X': (0, 1.01, 0.01),
        'name': 'Personal qualities',
        'terms': {
            'very low': ('trapmf', 0, 0, 0.15, 0.25),
            'low': ('trapmf', 0.15, 0.3, 0.4, 0.5),
            'average': ('trapmf', 0.35, 0.45, 0.7, 0.8),
            'high': ('trapmf', 0.55, 0.75, 1, 1),
        }
    },

    {
        'X': (0, 1.01, 0.01),
        'name': 'Knowledge',
        'terms': {
            'little knowledge': ('trapmf', 0, 0, 0.2, 0.33),
            'average knowledge': ('trapmf', 0.22, 0.35, 0.55, 0.66),
            'high knowledge': ('trapmf', 0.54, 0.7, 1, 1),
        }
    },

    {
        'X': (0, 1.01, 0.01),
        'name': 'Skills',
        'terms': {
            'low skilled': ('trapmf', 0, 0, 0.4, 0.5),
            'average skilled': ('trapmf', 0.35, 0.45, 0.7, 0.8),
            'high skilled': ('trapmf', 0.7, 0.75, 1, 1),
        }
    },

    {
        'X': (0, 1.01, 0.01),
        'name': 'Experience',
        'terms': {
            'no experience': ('trapmf', 0, 0, 0.10, 0.2),
            'small experience': ('trapmf', 0.10, 0.2, 0.4, 0.5),
            'medium experience': ('trapmf', 0.35, 0.45, 0.7, 0.8),
            'great experience': ('trapmf', 0.7, 0.8, 1, 1),
        }
    }
]

output_lv = {
    'X': (0, 1.01, 0.01),
    'name': 'Grade',
    'terms': {
        'very low': ('trapmf', 0, 0, 0.1, 0.2),
        'low': ('trimf', 0.1, 0.25, 0.33),
        'medium': ('trapmf', 0.25, 0.3, 0.4, 0.45),
        'above medium': ('trimf', 0.4, 0.5, 0.7),
        'high': ('trapmf', 0.6, 0.7, 0.8, 0.9),
        'extremely high': ('trapmf', 0.8, 0.95, 1, 1),
    }
}


rule_base = [
    (('very low', 'little knowledge', 'low skilled', 'no experience'), 'very low'),
    (('very low', 'little knowledge', 'low skilled', 'small experience'), 'very low'),
    (('very low', 'little knowledge', 'low skilled', 'medium experience'), 'very low'),
    (('very low', 'little knowledge', 'low skilled', 'great experience'), 'low'),
    (('very low', 'little knowledge', 'average skilled', 'no experience'), 'very low'),
    (('very low', 'little knowledge', 'average skilled', 'small experience'), 'low'),
    (('very low', 'little knowledge', 'average skilled', 'medium experience'), 'low'),
    (('very low', 'little knowledge', 'average skilled', 'great experience'), 'medium'),
    (('very low', 'little knowledge', 'high skilled', 'no experience'), 'medium'),
    (('very low', 'little knowledge', 'high skilled', 'small experience'), 'medium'),
    (('very low', 'little knowledge', 'high skilled', 'medium experience'), 'above medium'),
    (('very low', 'little knowledge', 'high skilled', 'great experience'), 'above medium'),
    (('very low', 'average knowledge', 'low skilled', 'no experience'), 'very low'),
    (('very low', 'average knowledge', 'low skilled', 'small experience'), 'low'),
    (('very low', 'average knowledge', 'low skilled', 'medium experience'), 'low'),
    (('very low', 'average knowledge', 'low skilled', 'great experience'), 'medium'),
    (('very low', 'average knowledge', 'average skilled', 'no experience'), 'low'),
    (('very low', 'average knowledge', 'average skilled', 'small experience'), 'medium'),
    (('very low', 'average knowledge', 'average skilled', 'medium experience'), 'medium'),
    (('very low', 'average knowledge', 'average skilled', 'great experience'), 'above medium'),
    (('very low', 'average knowledge', 'high skilled', 'no experience'), 'above medium'),
    (('very low', 'average knowledge', 'high skilled', 'small experience'), 'above medium'),
    (('very low', 'average knowledge', 'high skilled', 'medium experience'), 'above medium'),
    (('very low', 'average knowledge', 'high skilled', 'great experience'), 'high'),
    (('very low', 'high knowledge', 'low skilled', 'no experience'), 'low'),
    (('very low', 'high knowledge', 'low skilled', 'small experience'), 'medium'),
    (('very low', 'high knowledge', 'low skilled', 'medium experience'), 'medium'),
    (('very low', 'high knowledge', 'low skilled', 'great experience'), 'above medium'),
    (('very low', 'high knowledge', 'average skilled', 'no experience'), 'above medium'),
    (('very low', 'high knowledge', 'average skilled', 'small experience'), 'above medium'),
    (('very low', 'high knowledge', 'average skilled', 'medium experience'), 'above medium'),
    (('very low', 'high knowledge', 'average skilled', 'great experience'), 'high'),
    (('very low', 'high knowledge', 'high skilled', 'no experience'), 'high'),
    (('very low', 'high knowledge', 'high skilled', 'small experience'), 'high'),
    (('very low', 'high knowledge', 'high skilled', 'medium experience'), 'extremely high'),
    (('very low', 'high knowledge', 'high skilled', 'great experience'), 'extremely high'),
    (('low', 'little knowledge', 'low skilled', 'no experience'), 'very low'),
    (('low', 'little knowledge', 'low skilled', 'small experience'), 'very low'),
    (('low', 'little knowledge', 'low skilled', 'medium experience'), 'very low'),
    (('low', 'little knowledge', 'low skilled', 'great experience'), 'low'),
    (('low', 'little knowledge', 'average skilled', 'no experience'), 'very low'),
    (('low', 'little knowledge', 'average skilled', 'small experience'), 'low'),
    (('low', 'little knowledge', 'average skilled', 'medium experience'), 'low'),
    (('low', 'little knowledge', 'average skilled', 'great experience'), 'medium'),
    (('low', 'little knowledge', 'high skilled', 'no experience'), 'medium'),
    (('low', 'little knowledge', 'high skilled', 'small experience'), 'medium'),
    (('low', 'little knowledge', 'high skilled', 'medium experience'), 'above medium'),
    (('low', 'little knowledge', 'high skilled', 'great experience'), 'above medium'),
    (('low', 'average knowledge', 'low skilled', 'no experience'), 'low'),
    (('low', 'average knowledge', 'low skilled', 'small experience'), 'low'),
    (('low', 'average knowledge', 'low skilled', 'medium experience'), 'low'),
    (('low', 'average knowledge', 'low skilled', 'great experience'), 'medium'),
    (('low', 'average knowledge', 'average skilled', 'no experience'), 'medium'),
    (('low', 'average knowledge', 'average skilled', 'small experience'), 'medium'),
    (('low', 'average knowledge', 'average skilled', 'medium experience'), 'above medium'),
    (('low', 'average knowledge', 'average skilled', 'great experience'), 'above medium'),
    (('low', 'average knowledge', 'high skilled', 'no experience'), 'above medium'),
    (('low', 'average knowledge', 'high skilled', 'small experience'), 'above medium'),
    (('low', 'average knowledge', 'high skilled', 'medium experience'), 'high'),
    (('low', 'average knowledge', 'high skilled', 'great experience'), 'high'),
    (('low', 'high knowledge', 'low skilled', 'no experience'), 'medium'),
    (('low', 'high knowledge', 'low skilled', 'small experience'), 'medium'),
    (('low', 'high knowledge', 'low skilled', 'medium experience'), 'above medium'),
    (('low', 'high knowledge', 'low skilled', 'great experience'), 'above medium'),
    (('low', 'high knowledge', 'average skilled', 'no experience'), 'above medium'),
    (('low', 'high knowledge', 'average skilled', 'small experience'), 'above medium'),
    (('low', 'high knowledge', 'average skilled', 'medium experience'), 'above medium'),
    (('low', 'high knowledge', 'average skilled', 'great experience'), 'high'),
    (('low', 'high knowledge', 'high skilled', 'no experience'), 'high'),
    (('low', 'high knowledge', 'high skilled', 'small experience'), 'high'),
    (('low', 'high knowledge', 'high skilled', 'medium experience'), 'extremely high'),
    (('low', 'high knowledge', 'high skilled', 'great experience'), 'extremely high'),
    (('average', 'little knowledge', 'low skilled', 'no experience'), 'very low'),
    (('average', 'little knowledge', 'low skilled', 'small experience'), 'very low'),
    (('average', 'little knowledge', 'low skilled', 'medium experience'), 'low'),
    (('average', 'little knowledge', 'low skilled', 'great experience'), 'low'),
    (('average', 'little knowledge', 'average skilled', 'no experience'), 'low'),
    (('average', 'little knowledge', 'average skilled', 'small experience'), 'low'),
    (('average', 'little knowledge', 'average skilled', 'medium experience'), 'medium'),
    (('average', 'little knowledge', 'average skilled', 'great experience'), 'medium'),
    (('average', 'little knowledge', 'high skilled', 'no experience'), 'medium'),
    (('average', 'little knowledge', 'high skilled', 'small experience'), 'above medium'),
    (('average', 'little knowledge', 'high skilled', 'medium experience'), 'above medium'),
    (('average', 'little knowledge', 'high skilled', 'great experience'), 'above medium'),
    (('average', 'average knowledge', 'low skilled', 'no experience'), 'low'),
    (('average', 'average knowledge', 'low skilled', 'small experience'), 'low'),
    (('average', 'average knowledge', 'low skilled', 'medium experience'), 'medium'),
    (('average', 'average knowledge', 'low skilled', 'great experience'), 'medium'),
    (('average', 'average knowledge', 'average skilled', 'no experience'), 'medium'),
    (('average', 'average knowledge', 'average skilled', 'small experience'), 'medium'),
    (('average', 'average knowledge', 'average skilled', 'medium experience'), 'above medium'),
    (('average', 'average knowledge', 'average skilled', 'great experience'), 'above medium'),
    (('average', 'average knowledge', 'high skilled', 'no experience'), 'above medium'),
    (('average', 'average knowledge', 'high skilled', 'small experience'), 'above medium'),
    (('average', 'average knowledge', 'high skilled', 'medium experience'), 'high'),
    (('average', 'average knowledge', 'high skilled', 'great experience'), 'extremely high'),
    (('average', 'high knowledge', 'low skilled', 'no experience'), 'medium'),
    (('average', 'high knowledge', 'low skilled', 'small experience'), 'medium'),
    (('average', 'high knowledge', 'low skilled', 'medium experience'), 'above medium'),
    (('average', 'high knowledge', 'low skilled', 'great experience'), 'above medium'),
    (('average', 'high knowledge', 'average skilled', 'no experience'), 'above medium'),
    (('average', 'high knowledge', 'average skilled', 'small experience'), 'above medium'),
    (('average', 'high knowledge', 'average skilled', 'medium experience'), 'above medium'),
    (('average', 'high knowledge', 'average skilled', 'great experience'), 'high'),
    (('average', 'high knowledge', 'high skilled', 'no experience'), 'high'),
    (('average', 'high knowledge', 'high skilled', 'small experience'), 'high'),
    (('average', 'high knowledge', 'high skilled', 'medium experience'), 'extremely high'),
    (('average', 'high knowledge', 'high skilled', 'great experience'), 'extremely high'),
    (('high', 'little knowledge', 'low skilled', 'no experience'), 'very low'),
    (('high', 'little knowledge', 'low skilled', 'small experience'), 'very low'),
    (('high', 'little knowledge', 'low skilled', 'medium experience'), 'low'),
    (('high', 'little knowledge', 'low skilled', 'great experience'), 'low'),
    (('high', 'little knowledge', 'average skilled', 'no experience'), 'low'),
    (('high', 'little knowledge', 'average skilled', 'small experience'), 'low'),
    (('high', 'little knowledge', 'average skilled', 'medium experience'), 'medium'),
    (('high', 'little knowledge', 'average skilled', 'great experience'), 'medium'),
    (('high', 'little knowledge', 'high skilled', 'no experience'), 'medium'),
    (('high', 'little knowledge', 'high skilled', 'small experience'), 'above medium'),
    (('high', 'little knowledge', 'high skilled', 'medium experience'), 'above medium'),
    (('high', 'little knowledge', 'high skilled', 'great experience'), 'high'),
    (('high', 'average knowledge', 'low skilled', 'no experience'), 'low'),
    (('high', 'average knowledge', 'low skilled', 'small experience'), 'low'),
    (('high', 'average knowledge', 'low skilled', 'medium experience'), 'medium'),
    (('high', 'average knowledge', 'low skilled', 'great experience'), 'above medium'),
    (('high', 'average knowledge', 'average skilled', 'no experience'), 'medium'),
    (('high', 'average knowledge', 'average skilled', 'small experience'), 'medium'),
    (('high', 'average knowledge', 'average skilled', 'medium experience'), 'above medium'),
    (('high', 'average knowledge', 'average skilled', 'great experience'), 'above medium'),
    (('high', 'average knowledge', 'high skilled', 'no experience'), 'above medium'),
    (('high', 'average knowledge', 'high skilled', 'small experience'), 'above medium'),
    (('high', 'average knowledge', 'high skilled', 'medium experience'), 'high'),
    (('high', 'average knowledge', 'high skilled', 'great experience'), 'extremely high'),
    (('high', 'high knowledge', 'low skilled', 'no experience'), 'medium'),
    (('high', 'high knowledge', 'low skilled', 'small experience'), 'medium'),
    (('high', 'high knowledge', 'low skilled', 'medium experience'), 'above medium'),
    (('high', 'high knowledge', 'low skilled', 'great experience'), 'above medium'),
    (('high', 'high knowledge', 'average skilled', 'no experience'), 'above medium'),
    (('high', 'high knowledge', 'average skilled', 'small experience'), 'above medium'),
    (('high', 'high knowledge', 'average skilled', 'medium experience'), 'high'),
    (('high', 'high knowledge', 'average skilled', 'great experience'), 'high'),
    (('high', 'high knowledge', 'high skilled', 'no experience'), 'high'),
    (('high', 'high knowledge', 'high skilled', 'small experience'), 'extremely high'),
    (('high', 'high knowledge', 'high skilled', 'medium experience'), 'extremely high'),
    (('high', 'high knowledge', 'high skilled', 'great experience'), 'extremely high'),
]